name: CI

on:
  pull_request:
  push:

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Setup cache, id: cache, uses: actions/cache@v2, with: {path: _resources, key: "${{ runner.os }}-resources"}}
      - name: Download ffmpeg
        if: "steps.cache.outputs.cache-hit != 'true'"
        run: |
          mkdir _resources
          cd _resources
          wget --progress=dot:mega https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-{amd,arm}64-static.tar.xz{,.md5}
          find . -type f
          md5sum --check *.md5
      - {name: Setup Docker Buildx, uses: docker/setup-buildx-action@v1}
      - name: Build Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
